apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    concurrency: 3
  tagPolicy:
    customTemplate:
      template: "{{ printf \"%.10s\" .SHA}}"
      components:
        - name: SHA
          gitCommit:
            variant: CommitSha
  artifacts:
    - image: eshishkin/k8s-examples/sender-service
      context: sender-service
      jib:
        type: maven
    - image: eshishkin/k8s-examples/receiver-service
      context: receiver-service
      jib:
        type: maven

test:
  - image: eshishkin/k8s-examples/sender-service
    structureTests:
      - './etc/container-tests/common.yaml'
      - './etc/container-tests/sender-service-test.yaml'
  - image: eshishkin/k8s-examples/receiver-service
    structureTests:
      - './etc/container-tests/common.yaml'
      - './etc/container-tests/receiver-service-test.yaml'

deploy:
  helm:
    releases:
      - name: mongo
        chartPath: ./etc/k8s/charts/mongo
        upgradeOnChange: false
        wait: true

      - name: broker
        chartPath: ./etc/k8s/charts/message-broker
        upgradeOnChange: false
        wait: true

      - name: redis
        chartPath: ./etc/k8s/charts/redis
        upgradeOnChange: false
        wait: true

      - name: sender-service
        chartPath: ./etc/k8s/charts/sender-service
        recreatePods: false
        artifactOverrides:
          application.image: eshishkin/k8s-examples/sender-service

      - name: receiver-service
        chartPath: ./etc/k8s/charts/receiver-service
        recreatePods: false
        artifactOverrides:
          application.image: eshishkin/k8s-examples/receiver-service

profiles:
  - name: monitoring
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: mailer
          chartPath: ./etc/k8s/charts/mailer
          upgradeOnChange: false
          wait: true
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: monitoring-tools
          chartPath: ./etc/k8s/charts/monitoring-tools
          upgradeOnChange: false
          wait: true