apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  prometheus.yml: |-
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        version: 1
        editable: true

      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service:3100
        isDefault: false
        version: 1
        editable: false