apiVersion: v1
kind: Service
metadata:
  name: redis-server
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP

    - name: exporter
      port: 9121
      targetPort: 9121
      protocol: TCP

  selector:
    app: redis-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      annotations:
        prometheus/scrape_enabled: "true"
        prometheus/scrape_endpoint: "/metrics"
        prometheus/scrape_port: "9121"
      labels:
        app: redis-server
    spec:
      containers:
        - name: redis
          image: "redis:6.0.7"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.11.1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9121
