apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /sender/(.*)
            backend:
              serviceName: sender-service
              servicePort: 8080
          - path: /receiver/(.*)
            backend:
              serviceName: receiver-service
              servicePort: 8080