apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-service
  template:
    metadata:
      annotations:
        prometheus/scrape_enabled: "false"
        prometheus/scrape_endpoint: "/actuator/prometheus"
        prometheus/scrape_port: "8080"
      labels:
        app: mongo-service
    spec:
      containers:
        - name: mongo
          image: "mongo:4.2.7"
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#            initialDelaySeconds: 10
#            timeoutSeconds: 5
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 128Mi
