apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-service
  template:
    metadata:
      annotations:
        prometheus/scrape_enabled: "false"
      labels:
        app: mongo-service
    spec:
      containers:
        - name: mongo
          image: "mongo:4.2.7"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 128Mi
