
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    rule_files:
      - "alert.rules.yml"

    scrape_configs:
      - job_name: selfcheck
        static_configs:
          - targets: ['localhost:9090']

      - job_name: k8s-pod-checker
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_scrape_enabled]
            action: keep
            regex: true

          - source_labels: [__meta_kubernetes_pod_label_app]
            action: replace
            target_label: application

          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)

          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace

          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_scrape_endpoint]
            action: replace
            target_label: __metrics_path__

          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_scrape_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__

    alerting:
      alertmanagers:
        - static_configs:
          - targets: ['prometheus-alert-manager-service:9093']

  alert.rules.yml: |-
    groups:
    - name: example
      rules:
      - alert: MongoDown
        expr: mongodb_up == 0 OR absent(mongodb_up) == 1
        for: 1m
        labels:
          layer: db
          severity: high
        annotations:
          summary: Mongo is down
          message: Mongo is down

      - alert: HighCpuUtilization
        expr: rate(process_cpu_usage{app="receiver-service"}[5m]) >= 0.5
        for: 5m
        labels:
          layer: services
          severity: warn
        annotations:
          summary: High CPU utilization
          message: {{`"High CPU utilization (service: {{$labels.app}}, instance: {{$labels.instance}})"`}}