apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit-logger
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: fluent-bit-logger
  template:
    metadata:
      labels:
        app: fluent-bit-logger
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: "/api/v1/metrics/prometheus"
        fluentbit.io/exclude: "true"
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.5-debug
          imagePullPolicy: Always
          ports:
            - containerPort: 2020
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elastic-search"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
          volumeMounts:
            - name: varlog
              mountPath: /var/log

            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true

            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/

#            - name: mnt
#              mountPath: /mnt
#              readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: varlog
          hostPath:
            path: /var/log

        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config

#        - name: mnt
#          hostPath:
#            path: /mnt
      serviceAccountName: fluent-bit

